### ISSUE TITLE
Tinted items (detailed things, non-mainline)

### ISSUE THREAD

**Issue by teddyxlandlee** [Xdi8Mod/Xdi8aho-Mod#10]
Tinted dragon breath is introduced in #9, with brewing stand support.  
Now there are some issues:  

- [x] Should **tinted** honey bottles be craftable with Honey Bottle + 2 Amethyst Crystals?
- [x] Should **tinted** dragon breath be craftable with Dragon Breath + 2 Amethyst Crystals?
- [x] Should display name of tinted dragon breath being obfuscated _(Potion of Mystery)_? Dragon breath is known of magic, and somehow glints in texture (not foiled)
- [x] Should **tinted** honey bottles be craftable with 4 Tinted Glass Bottles + Honey Block?   
- [x] Should Tinted/Ordinary Honey Bottles be able to split out into Honey Block? (Using tag, recipe)

**Comment by QWERTY770** [comment]
1.Yes
2.Yes
3.Yes
4/5.Yes, but what does "/Ordinary" mean? Tinted honey bottles should only be craftable with tinted bottles. We don't need to change the recipes about ordinary bottles.

**Comment by teddyxlandlee** [comment]
Ordinary in 4 was mistake.  

5: I will not change vanilla recipe, or compatibility issue will occur. In fact, I'll use tag to write another recipe, so that ordinary & tinted honey bottles can fill honey block together.  
Anyway, players should recognize their honey "potions" by themselves, as the lang is obfuscated.
