### ISSUE TITLE
should fireflies be collected with tinted glass bottles?

### ISSUE THREAD

**Issue by QWERTY770** [Xdi8Mod/Xdi8aho-Mod#4]

**Comment by teddyxlandlee** [comment]
I asked my collaborators of SPM _(Sweet Potato Mod)_ about this and they gave me a **non-negative** answer. Some even requested a **net** to catch them but I'm not fond of that unless it'd be used on other mobs.  

Edit: are you hesitating whether or not they should be also collected with **ordinary bottles**? I disagree cuz I think they're afraid of sunlight.
